---
- name: Post-Upgrade OS Check
  hosts: all
  gather_facts: false

  tasks:
    - name: Debug with message "OS post-upgrade check ver"
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        msg: "OS post-upgrade check ver 1.0"

    - name: Add wait task 10s
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.wait_for:
        timeout: 10
